// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0gXkEHFqO5hGuNB1eQ2wf_UIXr0-BCQg',
    appId: '1:205139614258:web:159bedc01e3ca85716ba2b',
    messagingSenderId: '205139614258',
    projectId: 'tuwaiq-community',
    authDomain: 'tuwaiq-community.firebaseapp.com',
    storageBucket: 'tuwaiq-community.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHLGwJIfMh_QYcVs00mrlU184kfJr4a9Q',
    appId: '1:205139614258:android:6cdfb8b01a47047216ba2b',
    messagingSenderId: '205139614258',
    projectId: 'tuwaiq-community',
    storageBucket: 'tuwaiq-community.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYr2Vd_Ewxt_xdzQRSLkSUTVyT08rnY3I',
    appId: '1:205139614258:ios:b1e9c3ec6f74356a16ba2b',
    messagingSenderId: '205139614258',
    projectId: 'tuwaiq-community',
    storageBucket: 'tuwaiq-community.appspot.com',
    iosClientId: '205139614258-kpongl2oug5dink1t7ueqauj0c56ur99.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
